name: DEBUG

on:
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail'
  INSTALL_COMPILER_RETRIES: '5'
  JAVA_VERSION: '17'

permissions:
  contents: read

jobs:
  cpp-msvc-build:
    name: C++ MSVC (Windows)
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      CC: cl
      CXX: cl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache Gradle wrappers
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build
        run: |
          Write-Host "Installing ProcessMonitor ..."

          $dir = (get-location).path
          $client = New-Object System.Net.WebClient
          $client.DownloadFile("https://download.sysinternals.com/files/ProcessMonitor.zip", "$dir\ProcessMonitor.zip")
  
          Push-Location $dir
          Expand-Archive -LiteralPath "ProcessMonitor.zip" -DestinationPath "$dir"
          Remove-Item "ProcessMonitor.zip"
          Pop-Location
  
          Write-Host "Success: $dir\ProcessMonitor"
          
           $dir\ProcessMonitor\Procmon.exe /?
#          Start-Process -NoNewWindow $dir\ProcessMonitor\Procmon.exe /AcceptEula /Quiet /Backingfile $dir\procmon.log

#          cppbuild/cppbuild.ps1 --cxx-hide-deprecation-message --no-system-tests
      - name: Copy test logs
        id: copy_test_logs
        if: failure()
        run: |
          echo "file=build/distributions/test_logs.tbz2" | Out-File $env:GITHUB_OUTPUT -Encoding utf8 -Append
          ./gradlew tarTestLogs
      - name: Upload crash logs
        if: always() && steps.copy_test_logs.outputs.file == 'build/distributions/test_logs.tbz2'
        uses: actions/upload-artifact@v4
        with:
          name: crash-logs-msvc-latest
          path: ${{ steps.copy_test_logs.outputs.file }}
